spring:
  application:
    name: mytoken-eureka
  boot:
    admin:
      client:
        url: http://192.168.75.131:8084
  zipkin:
    base-url: http://192.168.75.131:9411

server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.75.131
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info