spring:
  application:
    name: mytoken-zuul
  boot:
    admin:
      client:
        url: http://192.168.75.131:8084
  zipkin:
    base-url: http://192.168.75.131:9411

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.75.131:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info